version: '3'

services:
  web:
    image: prophecies
    ports:
      - 8765:8765
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=60
      - DATABASE_URL=postgres://postgres:postgres@db/prophecies
      - ALLOWED_HOSTS=0.0.0.0,localhost
      - PORT=8765
      - DEBUG=false
    depends_on:
      - db
      - migration

  migration:
    build: .
    image: prophecies
    command: sh -c "/usr/bin/wait && pipenv run python manage.py migrate --noinput"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=60
      - DATABASE_URL=postgres://postgres:postgres@db/prophecies
    depends_on:
      - db

  db:
    image: "postgres:10.4"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prophecies
    command: postgres -c shared_preload_libraries=pg_stat_statements -c 'pg_stat_statements.track=all'
