version: 2

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - test-frontend:
          requires:
            - checkout
      - test-backend:
          requires:
            - checkout
jobs:
  checkout:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/repository/
    steps:
      - checkout
      - save_cache:
          name: Save the app bundle for downstream jobs
          key: repository-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repository/

  test-frontend:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/repository/
    steps:
      - restore_cache:
          name: Restore app bundle repository from the `checkout` job
          key: repository-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore node dependencies from previous builds
          key: node-dependencies-cache-{{ .Branch }}-{{ checksum "prophecies/apps/frontend/package.json" }}
      - run:
          name: Install node dependencies with yarn
          command: yarn
      - save_cache:
          name: Save dependencies cache for future builds
          key: node-dependencies-cache-{{ .Branch }}-{{ checksum "prophecies/apps/frontend/package.json" }}
          paths:
            - ./prophecies/apps/frontend/node_modules/
      - run:
          name: Run unit tests
          command: yarn test:unit

  test-backend:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repository/
    steps:
      - restore_cache:
          name: Restore app bundle repository from the `checkout` job
          key: repository-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore virtualenv from previous builds
          key: virtualenv-dependencies-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install pipenv and project's pip packages
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          name: Save virtualenv cache for future builds
          key: virtualenv-dependencies-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Run unit tests
          command: pipenv run python manage.py test prophecies
