version: 2

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - test-frontend:
          requires:
            - checkout
jobs:
  checkout:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/repository/
    steps:
      - checkout
      - save_cache:
          name: Save the app bundle for downstream jobs
          key: repository-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repository/

  test-frontend:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/repository/
    steps:
      - restore_cache:
          name: Restore app bundle repository from the `checkout` job
          key: repository-cache-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore node dependencies from previous builds
          key: node-dependencies-cache-{{ checksum "prophecies/apps/frontend/package.json" }}
      - run:
          name: Install node dependencies with yarn
          command: yarn
      - save_cache:
          name: Save dependencies cache for future builds
          key: node-dependencies-cache-{{ checksum "prophecies/apps/frontend/package.json" }}
          paths:
            - ./prophecies/apps/frontend/node_modules/
      - run:
          name: Run unit tests
          command: yarn test:unit
      - save_cache:
          name: Save the app bundle (repo + dependencies) for downstream jobs
          key: bundle-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repository/prophecies/apps/frontend/
