# Generated by Django 3.2.5 on 2021-07-26 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task name')),
                ('description', models.CharField(max_length=100, verbose_name='Task description')),
                ('rounds', models.PositiveIntegerField(default=3, verbose_name='Number of rounds')),
                ('automatic_round_attributions', models.BooleanField(default=True, verbose_name='Attribute rounds (if not checked, all checkers will participate in all rounds)')),
                ('allow_multiple_checks', models.BooleanField(default=True, verbose_name='Allow checkers to check several time the same item')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('allow_items_addition', models.BooleanField(default=False, verbose_name='Allow checker to add items')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChoicesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('choices_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taskchoicesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='checkers',
            field=models.ManyToManyField(related_name='task', through='core.TaskChecker', to=settings.AUTH_USER_MODEL, verbose_name="User in charge of checking this task's data"),
        ),
        migrations.AddField(
            model_name='task',
            name='choices_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskchoicesgroup', verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project this task belong to'),
        ),
    ]
