# Generated by Django 3.2.5 on 2021-07-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchoice',
            name='choices_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.taskchoicesgroup'),
        ),
    ]
