# Generated by Django 3.2.5 on 2021-07-26 19:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_constance_id'),
        ('core', '0002_alter_taskchoice_choices_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('database.constance',),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=colorfield.fields.ColorField(default='#31807D', max_length=18),
        ),
        migrations.AlterField(
            model_name='taskchoice',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
