# Generated by Django 3.2.6 on 2021-08-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_taskrecord_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='has_disagreements',
            field=models.BooleanField(default=False, help_text='Reviews are different'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='has_notes',
            field=models.BooleanField(default=False, help_text='One or more reviews have notes'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='locked',
            field=models.BooleanField(default=False, help_text='A user locked this task record'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked this task record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_task_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
