# Generated by Django 3.2.5 on 2021-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UID'),
        ),
    ]
