# Generated by Django 3.2.5 on 2021-07-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_taskrecord_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecordAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=None, null=True, verbose_name='Attribution round')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=7)),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Checker note')),
                ('alternative_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice')),
                ('task_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskrecord')),
            ],
            options={
                'get_latest_by': 'round',
                'unique_together': {('task_record_id', 'checker_id')},
            },
        ),
    ]
