# Generated by Django 3.2.5 on 2021-07-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_taskrecordattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recordLinkTemplate',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='A link template to build a link for each task record. Task record can override this value with their own link'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='An optional link to the record'),
        ),
        migrations.AlterField(
            model_name='taskrecordattribution',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskrecordattribution',
            name='task_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='core.taskrecord'),
        ),
    ]
