# Generated by Django 3.2.5 on 2021-07-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210730_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Project this task belong to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recordLinkTemplate',
            field=models.CharField(blank=True, help_text='A link template to build a link for each task record. Task record can override this value with their own link', max_length=1000, null=True, verbose_name='Record link template'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='link',
            field=models.CharField(blank=True, help_text='An optional link to the record', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional metadata for this record (in JSON)', null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='original_value',
            field=models.TextField(blank=True, help_text='Original value of the record', null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='rounds',
            field=models.PositiveIntegerField(default=0, help_text='Number of rounds this record was submitted to'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done')], default='PENDING', help_text="Status of the record. Set to done after it passes all task's rounds", max_length=8),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='suggested_value',
            field=models.TextField(blank=True, help_text='Suggested value to be reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='uid',
            field=models.CharField(blank=True, help_text='An optional unique identifier used to update task records in bulk', max_length=50, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='taskrecordattribution',
            name='alternative_value',
            field=models.TextField(blank=True),
        ),
    ]
