# Generated by Django 3.2.6 on 2021-08-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210830_1535'),
        ('core', '0005_notification'),
    ]

    operations = [
    ]
