# Generated by Django 3.2.5 on 2021-07-31 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20210731_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskchecker',
            unique_together={('checker', 'task')},
        ),
    ]
