# Generated by Django 3.2.6 on 2021-09-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_rename_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecordreview',
            name='note_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrecordreview',
            name='note_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
