# Generated by Django 3.2.5 on 2021-08-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_taskchecker_unique_together'),
    ]

    operations = [
        migrations.RenameModel('TaskRecordAttribution', 'TaskRecordReview'),
    ]
