# Generated by Django 3.2.7 on 2021-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20210907_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')],
                                   default='OPEN',
                                   help_text='Status of the task. Set to closed or locked will prevent any update of the records.',
                                   max_length=6),
        ),
    ]
