# Generated by Django 3.2.6 on 2021-08-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20210802_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrecord',
            old_name='suggested_value',
            new_name='predicted_value',
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='core.task'),
        ),
        migrations.AlterField(
            model_name='taskrecordreview',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskrecordreview',
            name='task_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.taskrecord'),
        ),
    ]
