# Generated by Django 3.2.6 on 2021-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210804_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='require_alternative_value',
            field=models.BooleanField(default=False, verbose_name='Requires an alternative value?'),
        ),
    ]
