# Generated by Django 3.2.7 on 2021-11-04 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_auto_20211001_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='settingvisibility',
            name='setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility',
                                       to='core.setting'),
        ),
    ]
