# Generated by Django 3.2.6 on 2021-08-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_choice_require_alternative_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('choice_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_values', to='core.choicegroup')),
            ],
        ),
    ]
