# Generated by Django 3.2.6 on 2021-08-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alternativevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecordreview',
            name='alternative_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
