# Generated by Django 3.2.9 on 2021-12-15 10:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_actionaggregation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionAggregation',
            new_name='ActionAggregate',
        ),
    ]
