# Generated by Django 3.2.6 on 2021-08-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_taskrecordreview_alternative_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecordreview',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.choice'),
        ),
    ]
