# Generated by Django 3.2.9 on 2022-01-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_actionaggregate'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='taskrecordreview',
            index_together={('checker_id', 'round', 'status'), ('checker_id', 'round')},
        ),
        migrations.CreateModel(
            name='TaskUserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(help_text='Round number of the static entry')),
                ('done_count', models.IntegerField(default=0, help_text='Count of done records')),
                ('pending_count', models.IntegerField(default=0, help_text='Count of pending records')),
                (
                'checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'unique_together': {('task_id', 'checker_id', 'round')},
            },
        ),
    ]
