# Generated by Django 3.2.9 on 2022-01-12 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_actionaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='saved_by',
            field=models.ManyToManyField(help_text='Users who saved this task record', related_name='saved_task_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
