# Generated by Django 3.2.6 on 2021-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_taskrecordreview_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecordreview',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Checker note'),
        ),
    ]
