# Generated by Django 3.2.9 on 2022-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_rename_recordlinktemplate_task_record_link_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embeddable_links',
            field=models.BooleanField(default=False,
                                      verbose_name='Allow end-users to preview links within an iframe (targeted website must allow it)'),
        ),
    ]
