# Generated by Django 3.2.9 on 2022-01-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_task_embeddable_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='embeddable_record_link_template',
            field=models.CharField(blank=True, help_text='An option link template to use within the link preview.',
                                   max_length=1000, null=True, verbose_name='Record link template'),
        ),
        migrations.AlterField(
            model_name='task',
            name='allow_items_addition',
            field=models.BooleanField(default=False, verbose_name='Allow checker to add items (not implemented yet)'),
        ),
    ]
