# Generated by Django 3.2.6 on 2021-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_choice_shortkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='shortkeys',
            field=models.CharField(blank=True, help_text='Commat separated list of shortkeys to pick this choice', max_length=100, null=True),
        ),
    ]
