# Generated by Django 3.2.9 on 2022-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_auto_20220113_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='embeddable_link',
            field=models.CharField(blank=True,
                                   help_text='An optional alternative link to preview the record in an iframe',
                                   max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='embeddable_record_link_template',
            field=models.CharField(blank=True,
                                   help_text='An optional alternative link template to use within the link preview.',
                                   max_length=1000, null=True, verbose_name='Embeddable record link template'),
        ),
    ]
