# Generated by Django 3.2.9 on 2022-01-13 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_taskrecord_saved_by'),
        ('core', '0017_auto_20220113_1634'),
    ]

    operations = [
    ]
