# Generated by Django 3.2.9 on 2022-01-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220114_1130'),
        ('core', '0018_merge_20220113_1718'),
    ]

    operations = [
    ]
