# Generated by Django 3.2.9 on 2022-01-19 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_merge_20220114_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='bookmarked_by',
            field=models.ManyToManyField(help_text='Users who bookmarked this task record', related_name='bookmarked_task_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
