# Generated by Django 3.2.9 on 2022-02-02 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_taskuserchoicestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, help_text='Users who bookmarked this task record',
                                         related_name='bookmarked_task_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskrecordreview',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
