# Generated by Django 3.2.9 on 2022-03-31 15:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_task_choice_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#73B782', 'Correct'), ('#FE6565', 'Incorrect'), ('#FFE980', 'Warning'), ('#BEBFBF', "Don't know")]),
        ),
    ]
