# Generated by Django 3.2.16 on 2023-12-20 10:18

from django.db import migrations, models
import django.db.models.deletion
import prophecies.core.models.task_record_media
import prophecies.core.validators.task_record_media


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_choice_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecordMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=prophecies.core.models.task_record_media.task_record_media_directory_path, validators=[prophecies.core.validators.task_record_media.MimeTypeValidator()])),
                ('uid', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=128)),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='core.task')),
                ('task_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.taskrecord')),
            ],
        ),
    ]
