# Generated by Django 3.2.16 on 2023-12-20 16:28

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_record_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#73B782', 'Correct'), ('#FE6565', 'Incorrect'), ('#FFE980', 'Warning'), ('#BEBFBF', "Don't know")]),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=colorfield.fields.ColorField(default='#31807D', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.task'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='uid',
            field=models.CharField(blank=True, help_text='An optional unique identifier used to update task records in bulk', max_length=100, null=True, verbose_name='UID'),
        ),
    ]
