# Generated by Django 3.2.16 on 2023-12-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20231220_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecordmedia',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_record_medias', to='core.task'),
        ),
    ]
