# Generated by Django 3.2.16 on 2024-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_taskrecordmedia_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='TextTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='template_type',
            field=models.CharField(choices=[('TEXT', 'Text Task'), ('MEDIA', 'Media Task')], default='TEXT', max_length=16),
        ),
    ]
