# Generated by Django 3.2.16 on 2024-01-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0028_auto_20240103_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.tasktemplatesetting_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.DeleteModel(
            name='MediaTask',
        ),
        migrations.DeleteModel(
            name='TextTask',
        ),
        migrations.AlterField(
            model_name='task',
            name='template_type',
            field=models.CharField(choices=[('TEXT', 'Text Task'), ('MEDIA', 'Media Task'), ('IFRAME', 'Iframe Task')], default='TEXT', help_text='Template type to use to display the task.', max_length=16),
        ),
        migrations.CreateModel(
            name='TaskTemplateSettingForIframe',
            fields=[
                ('tasktemplatesetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tasktemplatesetting')),
                ('max_width', models.IntegerField(blank=True, null=True)),
                ('max_height', models.IntegerField(blank=True, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('display_original_value', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.tasktemplatesetting',),
        ),
        migrations.CreateModel(
            name='TaskTemplateSettingForMedia',
            fields=[
                ('tasktemplatesetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tasktemplatesetting')),
                ('max_width', models.IntegerField(blank=True, null=True)),
                ('max_height', models.IntegerField(blank=True, null=True)),
                ('display_original_value', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.tasktemplatesetting',),
        ),
        migrations.CreateModel(
            name='TaskTemplateSettingForText',
            fields=[
                ('tasktemplatesetting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.tasktemplatesetting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.tasktemplatesetting',),
        ),
        migrations.AddField(
            model_name='task',
            name='template_setting',
            field=models.ForeignKey(blank=True, help_text='Each template type has its own set of settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='core.tasktemplatesetting'),
        ),
    ]
