# Generated by Django 4.2.9 on 2024-01-17 23:13

from django.db import migrations, models
import django.db.models.deletion

def migrate_pending_to_unassigned(apps, schema_editor):
    TaskRecord = apps.get_model('core', 'TaskRecord')
    TaskRecord.objects.filter(status='PENDING').update(status='UNASSIGNED')

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0029_auto_20240112_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template_setting',
            field=models.OneToOneField(blank=True, help_text='Each template type has its own set of settings (generated after template template is known)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='core.tasktemplatesetting'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('DONE', 'Done')], default='UNASSIGNED', help_text="Status of the record. Set to done after it passes all task's rounds", max_length=10),
        ),
        migrations.AlterField(
            model_name='tasktemplatesetting',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(migrate_pending_to_unassigned, migrations.RunPython.noop)
    ]
