# Generated by Django 5.1.5 on 2025-01-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_task_template_setting_alter_taskrecord_status_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskrecordreview',
            new_name='core_taskre_checker_bf3683_idx',
            old_fields=('checker_id', 'round'),
        ),
        migrations.RenameIndex(
            model_name='taskrecordreview',
            new_name='core_taskre_checker_8de86c_idx',
            old_fields=('checker_id', 'round', 'status'),
        ),
    ]
