# Generated by Django 5.1.5 on 2025-06-27 15:45

import prophecies.core.models.task_record_media
import prophecies.core.validators.task_record_media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_taskrecordreview_checker_id_round_core_taskre_checker_bf3683_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecordmedia',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to the file, if it is stored externally.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taskrecordmedia',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=prophecies.core.models.task_record_media.task_record_media_directory_path, validators=[prophecies.core.validators.task_record_media.MimeTypeValidator()]),
        ),
    ]
