from .alternative_value_admin import AlternativeValueAdmin
from .choice_group_admin import ChoiceGroupAdmin
from .project_admin import ProjectAdmin
from .setting_admin import *
from .task_admin import TaskAdmin
from .task_template_setting_admin import TaskTemplateSettingAdmin
from .task_record_admin import TaskRecordAdmin
from .task_record_media_admin import TaskRecordMediaAdmin
from .task_record_review_admin import TaskRecordReviewAdmin
from .tip_admin import TipAdmin
