export {
  ArrowRightIcon,
  BellIcon,
  ChevronDownIcon,
  CodeIcon,
  ClockIcon,
  CommandIcon,
  FrownIcon,
  FilterIcon,
  GridIcon,
  HomeIcon,
  LifeBuoyIcon,
  LogOutIcon,
  MessageSquareIcon,
  SearchIcon,
  ShieldIcon,
  SmileIcon,
  TrelloIcon,
  UsersIcon
} from 'vue-feather-icons'
