from .abstract_upload_form import AbstractUploadForm
from .alternative_value_upload_form import AlternativeValueUploadForm
from .task_record_assign_form import TaskRecordAssignForm
from .task_record_upload_form import TaskRecordUploadForm
from .task_record_media_upload_form import TaskRecordMediaUploadForm
from .setting_form import SettingForm
