name: Prophecies - CI

on:
  push:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-backend:
    uses: ./.github/workflows/python_task.yml
    with:
      python-version: '["3.9"]'
      command: poetry run pylint prophecies

  test-backend:
    uses: ./.github/workflows/python_task.yml
    with:
      python-version: '["3.9", "3.10"]'
      command: make test-back

  test-frontend:
    uses: ./.github/workflows/node_task.yml
    with:
      node-version: '["16.x", "18.x"]'
      command: make test-front
