name: Prophecies - CI

on:
  push:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-backend:
    uses: ./.github/workflows/python_task.yml
    with:
      python-version: '["3.9"]'
      command: poetry run pylint prophecies

  test-backend:
    uses: ./.github/workflows/python_task.yml
    with:
      python-version: '["3.9", "3.10"]'
      command: make test-back

  test-frontend:
    uses: ./.github/workflows/node_task.yml
    with:
      node-version: '["16.x", "18.x"]'
      command: make test-front

  docker-publish:
    needs: [lint-backend, test-backend, test-frontend]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV   

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare tag name
        id: prep
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: icij/prophecies:${{ env.TAG_NAME }},icij/prophecies:latest
          platforms: linux/amd64,linux/arm64